### ISSUE TITLE
Element nesting and text support

### ISSUE THREAD

**Issue by Firedrake969** [Jxck/html2json#9]
At the moment, you cannot nest inline elements, and text is always put before any children elements.  I understand that this project is for HTML 4, not 5, but would you (@Jxck) mind checking my fork out and giving me your thoughts on my improvements/fixes (namely element nesting and text support)?  Thanks!

**Comment by Jxck** [comment]
LGTM thanks !

you solved my long time TODO, so PR are welcome :)

**Comment by Jxck** [comment]
this is out dated, I released v1.0.0 with lots of breaking changes.
please check it out.
